```{r}
library(tidyverse)
library(tidyquant)
tidyquant::quandl_api_key("iJ-hS_bzUmiZE9_xv-ah")
tick <- c("CHRIS/CME_CL1", "CHRIS/CME_RB1")
df.prices <- tick %>%
  tidyquant::tq_get(get = "quandl", from = "2016-01-01") %>%
  stats::na.omit()

df.ret <- df.prices %>%
  dplyr::mutate(
    series = gsub(pattern = "CHRIS/CME_", "", symbol),
    value = dplyr::case_when(grepl("RB1", series) ~ settle * 42,
                             TRUE ~ settle)
  ) %>%
  dplyr::select(date, series, value) %>%
  dplyr::filter(date < as.Date("2020-01-01")) %>%
  dplyr::group_by(series) %>%
  dplyr::mutate(ret = value - dplyr::lag(value)) %>% #absolute returns
  stats::na.omit()

df.ret.wide <- df.ret %>%
  tidyr::pivot_wider(-value, values_from = ret, names_from = series)

fig.title = paste(colnames(df.ret.wide)[2],
                  "vs",
                  colnames(df.ret.wide)[3],
                  "Relationship")

axis.lim <- df.ret.wide %>% select(-date)

df.ret.wide %>% ggplot(aes(x = CL1, y = RB1, col = date)) + 
  geom_point() + 
  ylim(-10, 10) + xlim(-10, 10) + 
  labs(title = fig.title)

```

```{r}
df.ret.wide
fit <- stats::lm(RB1 ~ CL1, df.ret.wide)
summary(fit)
```

```{r}
broom::augment(fit) %>%
  ggplot(aes(x = CL1, y = RB1)) + geom_point() +
  stat_smooth(method = lm, se = FALSE) +
  geom_segment(aes(xend = CL1, yend = .fitted),
               color = "orange",
               size = 0.2) +
  ylim(-10, 10) + xlim(-10, 10) +
  labs(title = fig.title)
```

```{r}
library(ggfortify)
summary(fit)$coefficients
autoplot(fit,size=0.5)
```

```{r}
stats::acf(df.ret.wide$RB1 %>% na.omit())
stats::acf(resid(fit))
```

```{r hedge ratio}
fit$coefficients
```



```{r}
fig.title = "RBOB Forward Curves"
library(RTL)

df <- tq_get(c(paste("CHRIS/CME_RB", 1:36, sep = "")),
             get  = "quandl",
             from = "2010-01-01",
             to = as.character(Sys.Date()))
dflong <-
  df %>% dplyr::mutate(symbol = gsub("CHRIS/CME_", "", symbol)) %>%
  dplyr::transmute(date = date,
                   series = symbol,
                   value = settle)

dfwide <-
  dflong %>% tidyr::pivot_wider(names_from = series, values_from =  value)


RTL::chart_fwd_curves(
  df = as.data.frame(dfwide),
  cmdty = "cmewti",
  weekly = TRUE,
  main = fig.title,
  ylab = "$ per gallon",
  xlab = "",
  cex = 2
)
```
From Nov to Feb stocks go up but from March ot Oct they decrease a lot.
```{r}
EIAkey <- "4d1df1f2cab976fcda3c066a4723d720"

eia_df <- tibble::tribble(
  ~ ticker,
  ~ series,
  "PET.WGTSTUS1.W",
  "RBOB Stock"
) %>%
  dplyr::mutate(key = EIAkey) %>%
  dplyr::mutate(df = purrr::pmap(list(ticker, key), .f = RTL::eia2tidy)) %>%
  dplyr::select(series, df) %>% tidyr::unnest()

dat = c(name = "RBOB Stock", units = "Thousand Barrels")
fig.title = paste(dat["name"], "Seasonality")

dat2 = eia_df %>% dplyr::filter(series == dat["name"]) %>%
  dplyr::mutate(year = as.factor(year(date)),
                dateplot = lubridate::ymd(paste(c(lubridate::year(Sys.Date()), "01", "01"),
                                                collapse = "")) + 
                           lubridate::yday(date)) %>% 
  filter(date>="2016-01-01") %>% 
  ggplot(aes(
    x = dateplot,
    y = value,
    group = year,
    col = year
  )) +
  geom_line() + scale_x_date(date_breaks = "1 month", date_labels =  "%b") +
  labs(
    title = fig.title,
    subtitle = "How would you forecast from your SD balance? \nWhat happens to NG Futs time spreads when storage is seasonally low/high?",
    x = "",
    y = dat["units"]
  )
plotly::ggplotly(dat2)
```
```{r}
library(tsibble)
# Select our data, convert to tsibble and assign a year variable
tsi <- eia_df %>%
  dplyr::filter(date >= "2010-01-01") %>%
  tsibble::as_tsibble(key = series, index = date) %>%
  tsibble::group_by_key() %>%
  tsibble::index_by(freq = ~ yearmonth(.)) %>%
  dplyr::summarise(value = mean(value), .groups = c("keep")) %>%
  dplyr::mutate(change = value - lag(value)) %>% na.omit()
library(feasts)
tsi %>% autoplot(value)

tsi %>% feasts::gg_season(value)
tsi %>% feasts::gg_subseries(value)
tsi %>% feasts::ACF(value) %>% autoplot() + ggtitle("ACF on Values")
tsi %>% feasts::ACF(change) %>% autoplot() + ggtitle("ACF on Changes")

```


```{r}
tsi %>%
  fabletools::model(feasts::STL(value ~ season(window = Inf))) %>%
  fabletools::components() %>%
  autoplot()

tsi %>% fabletools::features(value,feat_stl)
```

```{r}
df <-
  tickers_eia %>% dplyr::filter(grepl(pattern = "mogas.*dayssupply", x = tick.r)) %>%
  dplyr::mutate(key = EIAkey) %>%
  dplyr::mutate(df = purrr::pmap(list(tick.eia, key, tick.r), .f = RTL::eia2tidy)) %>%
  dplyr::select(df) %>% tidyr::unnest(df)
fig.title = "STL"
RTL::chart_zscore(
  df = df,
  title = fig.title,
  per = "yearweek",
  output = "stl",
  chart = "seasons"
)
fig.title = "STL Stats"
RTL::chart_zscore(
  df = df,
  title = fig.title,
  per = "yearweek",
  output = "stats",
  chart = "seasons"
)
fig.title = "Z Scores"
RTL::chart_zscore(
  df = df,
  title = fig.title,
  per = "yearweek",
  output = "zscore",
  chart = "seasons"
)
fig.title = "Seasonal"
RTL::chart_zscore(
  df = df,
  title = fig.title,
  per = "yearweek",
  output = "seasonal",
  chart = "seasons"
)
```



















